name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency: build

jobs:
  test:
    runs-on: debian-12
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '21.6.0'
      - name: Test Bismuth
        run: |
          echo 'githubtester="true"' >> .env
          npm install
          node .